In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [19]:
l=[1,2,3,4]
print("list:",l)
print(type(l))
one_d_array = np.array(l)
print("numpy array:",one_d_array)
print(type(one_d_array))

list: [1, 2, 3, 4]
<class 'list'>
numpy array: [1 2 3 4]
<class 'numpy.ndarray'>


In [15]:
la=[1,2],[3,4]
print("list:",la)
print(type(l))
two_d_array=np.array(la)
print(two_d_array)
print(type(two_d_array))

list: ([1, 2], [3, 4])
<class 'list'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [14]:
k=[[[1,2,5],[3,4,6],[5,6,8]]]
print(type(k))
three_d_array=np.array(k)
print(three_d_array)
print(type(three_d_array))

<class 'list'>
[[[1 2 5]
  [3 4 6]
  [5 6 8]]]
<class 'numpy.ndarray'>


In [21]:
print("one d array dimension:",one_d_array.ndim)
print("one d array shape:",one_d_array.shape)
print("one d array size:",one_d_array.size)
print("\n")
print("two d array dimension:",two_d_array.ndim)
print("two d array shape:",two_d_array.shape)
print("two d array size:",two_d_array.size)
print("\n")
print("three d array dimension:",three_d_array.ndim)
print("three d array shape:",three_d_array.shape)
print("three d array size:",three_d_array.size)

one d array dimension: 1
one d array shape: (4,)
one d array size: 4


two d array dimension: 2
two d array shape: (2, 2)
two d array size: 4


three d array dimension: 3
three d array shape: (1, 3, 3)
three d array size: 9


In [23]:
import sys
sample_list = [0,1,2,3,4,5,6,7,8,9]
print("memory cons by an element",sys.getsizeof(sample_list[0]))
print("total memory usage",(sys.getsizeof(sample_list[0]))*len(sample_list))

memory cons by an element 28
total memory usage 280


In [25]:
numpy_array = np.array( [0,1,2,3,4,5,6,7,8,9])
print("memory cons by an element",numpy_array.itemsize)
print("total memory usage",numpy_array.itemsize*numpy_array.size)

memory cons by an element 4
total memory usage 40
